### ISSUE TITLE
Adjusting line-height

### ISSUE THREAD

**Issue by kkga** [barvian/fluid-tailwind#18]
Is there a way to adjust the calculated line-height for fluid font size?

I've tried additionally specifying `~leading-X/Y`, but the line-height baked into the `~text-X/Y` takes precedence. Adding the bang (`~leading-X/Y!`) also doesn't seem to be supported as tailwind breaks to compile.

P.S. Thanks for making this btw, it feels much nicer to use than some other fluid type alternatives.

**Comment by barvian** [comment]
Great catch! I just fixed this in v0.2.1. Also, it shouldn't be necessary any more, but you can mark fluid utilities important by adding the exclamation mark to the front, i.e. `!~leading-4/6` (I might want to add this to the docs)
