### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by Ondreas** [barvian/fluid-tailwind#22]
Would it be possible to create/register an ```npm``` package so we can use this plugin in [TailwindCSS online playground](https://play.tailwindcss.com) ?

Currently, when adding the plugin into the ```tailwind.config.js``` based on the plugin instructions, it throws an error:
```SyntaxError: Cannot use import statement outside a module.```

**Comment by barvian** [comment]
Hi, there's an npm package already, but it appears to not work with skypack (which is what Tailwind Play uses to require modules). Also, it seems that Tailwind Play doesn't support custom extractors, so the current syntax wouldn't work there anyway :/
