### ISSUE TITLE
The font-size value is not set when he's greater than 5xl even after passing the value to REM. 

### ISSUE THREAD

**Issue by LuckyFox31** [barvian/fluid-tailwind#23]
Hello,

I'm having a problem trying to use the plugin on the font size.

Here's the class I use: 
```
~text-lg/6xl 
```

And this is what is generated in the CSS: 
![CleanShot 2024-05-26 at 14 45 48@2x](https://github.com/barvian/fluid-tailwind/assets/35273245/8c39c316-7afd-48eb-9a52-9156aeea5a76)

Here is my tailwind configuration: 
```js
import fluid, { extract, screens, fontSize } from 'fluid-tailwind';

/** @type {import('tailwindcss').Config} */
export default {
  content: {
    files: [
      ...
    ],
    extract,
  },
  theme: {
    screens,
    fontSize,
    extend: {
      ...
    },
  },
  plugins: [fluid],
};
```

Can you please help me?

**Comment by barvian** [comment]
Hey, thanks for filing. That range is so big that it would [create an accessibility error](https://fluid.tw/#fluid-type-accessibility-errors), so the plugin doesn't output it by default. There's normally a CSS comment left in its place with more information, but it looks like it got stripped out (maybe after minification?). You can disable accessibility checks for fluid type like this:

```js title="tailwind.config.js" ins={6}
// ...
export default {
  // ...
  plugins: [
    fluid({
      checkSC144: false // default: true
    })
  ]
}
```
