### ISSUE TITLE
Arbitrary values are not working

### ISSUE THREAD

**Issue by krishnabrchand** [barvian/fluid-tailwind#25]
Arbitrary values are not working:
~text-[2rem]/[4rem]
~py-[2rem]/[4rem]

**Comment by barvian** [comment]
Hi, could you share your config/setup? I'm not able to reproduce this locally. It does appear that they're broken on Tailwind Play, if that's what you're seeing: https://play.tailwindcss.com/TtzXK6R9I1 (Tailwind Play seems to override the `content.extract` option); I can add a note about it 🫤

**Comment by barvian** [comment]
Tailwind Play & Play CDN users: I've opened [an issue](https://github.com/tailwindlabs/tailwindcss/issues/13766) for this
