### ISSUE TITLE
Getting 'Not fluid type' error for all usages of plugin

### ISSUE THREAD

**Issue by wilsonhou** [barvian/fluid-tailwind#28]
<img width="716" alt="Screenshot 2024-05-31 at 8 16 57 pm" src="https://github.com/barvian/fluid-tailwind/assets/52393809/ca5e706d-f503-40bc-a573-2b2f50c1d401">

Getting this error whenever i use the plugin 

Here's `package.json`
<img width="489" alt="Screenshot 2024-05-31 at 8 17 23 pm" src="https://github.com/barvian/fluid-tailwind/assets/52393809/83fe1c6a-af30-481e-8439-7866e7511b45">

**Comment by barvian** [comment]
Hi, it looks like you're using Tailwind's default theme which requires some tweaks (see [this section in the docs](https://fluid.tw/#tailwinds-default-theme)). Open to suggestions for the documentation around this 🤔
