### ISSUE TITLE
Plugin don't work - no css is generated

### ISSUE THREAD

**Issue by RichForever** [barvian/fluid-tailwind#35]
I'm trying to setup this plugin with my Wordpress project. So here's my tailwind.theme.config.js file

`const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
   "container": {
      "center": true,
   },
   "colors": { /* colors here */   },
   "fontSize": {
      "heading-1": "clamp(1rem, 10vw, 2rem)",
      "heading-2": "clamp(1rem, 10vw, 2rem)",
      "heading-3": "clamp(1rem, 10vw, 2rem)",
      "heading-4": "clamp(1rem, 10vw, 2rem)",
      "body": "clamp(1rem, 10vw, 2rem)",
      "body-small": "clamp(1rem, 10vw, 2rem)",
      "caption": "clamp(1rem, 10vw, 2rem)",
   },
   "fontFamily": {
      "inter": ['Inter', ...defaultTheme.fontFamily.sans],
      "playfair": ['Playfair Display', ...defaultTheme.fontFamily.sans],
   },
}
`

and this is my main tailwind config file

`import themeConfig from './tailwind.theme.config'
import fluid, { extract } from 'fluid-tailwind'

module.exports = {
    content: {
        files: [
            "./blocks/**/*.{php,twig,html,js}",
            "./lib/**/*.php",
            "./src/**/*.js",
            "./views/**/*.twig",
            "./*.{php,twig,html}",
        ],
        extract: extract
    },
    theme: {
        extend: {
            colors: themeConfig.colors,
            fontSize: themeConfig.fontSize,
            fontFamily: themeConfig.fontFamily,
            container: themeConfig.container,
        },
    },
    plugins: [
        require('flowbite/plugin'),
        fluid
        // require('@tailwindcss/forms')
    ],
    safelist: [
        'navbar.active',
    ]
}`

When I'm generating css within webpack all of the standard TW classes are generated but no any css for this plugin. What am I doing wrong?

I'm using newest version of plugin

**Comment by RichForever** [comment]
Problem solved, I have to add screens into my configuration. I think it's missing in the docs that this is required

**Comment by barvian** [comment]
Thanks for the feedback. I used to have a third installation step for the screens but I thought it was awkward without understanding the limitations first. What would you think about this as a third installation step instead?

> **3: Continue reading to the end of the [limitations section](#limitations)**
> 
>  There may be additional installation steps depending on your Tailwind configuration.

**Comment by RichForever** [comment]
I think I'll do it more clear. If you're using Tailwind version below 4 or you have custom screen definitions in pixels then go to step. Something like this. Also, I would add if you have default config then you must add this screens object
