### ISSUE TITLE
Feature request: support for use alongside tailwind-merge and `cn()`-like patterns

### ISSUE THREAD

**Issue by firxworx** [barvian/fluid-tailwind#36]
I have to start by saying this plugin is **INSANELY AWESOME** and **THANK-YOU** so much for investing your time and brilliance into it and releasing it to the world.

I was mucking around with my own approaches to fluidity with tailwind until I stumbled upon fluid.tw and you have taken it to a whole other level and made the tool a dream to use.

**Feature Request**

I would kindly _love_ for `tailwind-merge` to be officially supported.

I imagine the community would agree and this would remove a significant barrier for fluid.tw to emerge as one of the hottest tools in the tailwind ecosystem (if you even care about that!)

Support could be in the form of documentation, exporting a tailwind-merge config, or even releasing a [plugin](https://github.com/dcastil/tailwind-merge/blob/v2.3.0/docs/writing-plugins.md) for it.

**Motivation**

 `tailwind-merge` is a hugely popular tool that [thoughtfully merges](https://github.com/dcastil/tailwind-merge/blob/v2.3.0/docs/features.md) tailwind classes/utilities with 2.2M+ weekly downloads per npm.

One of the most common patterns seen in newer tailwind projects, which as arguably popularized-to-the-moon by the well-known [shadcn/ui](https://ui.shadcn.com/) component "library" is the `cn()` recipe. It is used to support the creation of readily resusable and customizable components:

```ts
import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
```

Of course a stock configuration of tailwind-merge has no idea what `~` is so any fluid.tw utilities created with the extractor are treated as unrecognized custom classes.

In my own mucking about with custom classes/utilities for fluidity in a tailwind preset I found I pretty much immediately needed to create a customized tailwind-merge and `cn()` to work with any of the leading tailwind-based component libraries and snippets websites du jour.

**References**

- https://www.npmjs.com/package/tailwind-merge
- https://github.com/dcastil/tailwind-merge/blob/v2.3.0/docs/configuration.md
- https://github.com/dcastil/tailwind-merge/blob/v2.3.0/docs/writing-plugins.md

Discussion question from 2 weeks ago that's related: https://github.com/barvian/fluid-tailwind/discussions/29

**Comment by barvian** [comment]
Hey, thanks for the kind words and feedback! I have a tailwind-merge plugin in the works, but it currently doesn't work well with the fluid variants (i.e. `~sm/lg` and `~@sm/lg`). I submitted [a PR](https://github.com/dcastil/tailwind-merge/pull/440) to tailwind-merge to better support them, so I'll report back depending on what happens with that 🙂

**Comment by barvian** [comment]
I just pushed an official plugin for tailwind-merge! [Check out the docs here](https://fluid.tw/#tailwind-merge). Huge thanks to @dcastil for adding an experimental config option to tailwind-merge 2.4.0 that can accommodate the variants in `fluid-tailwind` (among other things)!

I'm closing this for now. Feel free to open an issue if you encounter a bug with the plugin :)
