### ISSUE TITLE
Tailwind's Arbitrary Breakpoints Broken

### ISSUE THREAD

**Issue by ilbrigz** [barvian/fluid-tailwind#38]
```
<div class="min-[20rem]:text-center max-[40rem]:bg-sky-300"> asdfasf </div>
```

tailwind.config.mjs
```
import fluid, { extract, screens, fontSize } from "fluid-tailwind";
/** @type {import('tailwindcss').Config} */
export default {
  content: {
    files: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
    extract,
  },
  theme: {
    screens,
    fontSize,
  },
  plugins: [fluid],
};
```

Is there something wrong with me setup? Removing the plugin makes Arbitrary Breakpoints working again.

**Comment by barvian** [comment]
Hi, thanks for filing 👋. Is there anything else in your tailwind config? The arbitrary breakpoints work locally for me with your config.

**Comment by ilbrigz** [comment]
Strange. I'm also unable to replace the same problem on a new astro app. There could be something wrong with my code. Sorry
