### ISSUE TITLE
ESM / CJS issues using programmatically

### ISSUE THREAD

**Issue by Cherry** [barvian/fluid-tailwind#39]
Reproduction: https://github.com/Cherry/tailwind-fluid-cjs-repro

We have a workflow where we use Tailwind to generate a static "theme" output using `resolveConfig`. An example of this can be seen in the `generate-theme.js` file.

- With Fluid disabled, this works without issue
- However, if you uncomment line 1 in `tailwind.config.js` to enable Fluid, the `generate-theme.js` file will throw an error like so:

```
E:\GitHub\tailwind-fluid-cjs-repro\node_modules\fluid-tailwind\dist\index.js:8
var mapObject = require('map-obj');
                ^

Error [ERR_REQUIRE_ESM]: require() of ES Module E:\GitHub\tailwind-fluid-cjs-repro\node_modules\map-obj\index.js from E:\GitHub\tailwind-fluid-cjs-repro\node_modules\fluid-tailwind\dist\index.js not supported.
Instead change the require of E:\GitHub\tailwind-fluid-cjs-repro\node_modules\map-obj\index.js in E:\GitHub\tailwind-fluid-cjs-repro\node_modules\fluid-tailwind\dist\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (E:\GitHub\tailwind-fluid-cjs-repro\node_modules\fluid-tailwind\dist\index.js:8:17) {
  code: 'ERR_REQUIRE_ESM'
}
```

Using Node.js v20.15.1

Full reproduction steps:

- Clone linked reproduction repo
- npm ci
- Run `node generate-theme.js`, observe no issues
- Uncomment line 1, 7, and 13 in `tailwind.config.js`
- Re-run `node generate-theme.js`, observe errors

**Comment by barvian** [comment]
Hey, thanks a lot for the repro. I just pushed v1.0.3 which fixes this for me locally. Feel free to comment if you're still experiencing issues!

**Comment by Cherry** [comment]
That seems to work great, thank you so much for the quick resolution!
