### ISSUE TITLE
Clamp doesn't work

### ISSUE THREAD

**Issue by draylegend** [barvian/fluid-tailwind#41]
Config doesn't work for me in an nx/angular workspace with tailwind. [Repo](https://github.com/draylegend/fluid-tailwind)

#### Smartphone view

![image](https://github.com/user-attachments/assets/8ce78101-7b33-4d4b-8674-639acb52d46b)

#### Tablet view

![image](https://github.com/user-attachments/assets/f286cd33-d915-406e-bf08-4b60e22a0271)

**Comment by barvian** [comment]
Hey, thanks for the repro. I wasn't able to run your project locally, but it looks like it's missing the extractor from the [installation section](https://fluid.tw/#installation). Curious to hear if that fixes it for you 👍

**Comment by draylegend** [comment]
I tried to sue extractor but it didn't work, then I copied the config from the playground.

Changed the tailwind config to the installation instructions accordingly.

@barvian you can use `npm` to install deps if you don't have bun

**Comment by barvian** [comment]
> I tried to use extractor but it didn't work, then I copied the config from the playground.
> 
> Changed the tailwind config to the installation instructions accordingly.
> 
> @barvian you can use `npm` to install deps if you don't have bun

Hi, I installed the dependencies fine with `bun` but I didn't know how to run the actual project from there

**Comment by draylegend** [comment]
`nx serve client`

**Comment by barvian** [comment]
Gotcha, thanks. I was able to get it working locally with this config:

```diff
const { createGlobPatternsForDependencies } = require('@nx/angular/tailwind');
const { join } = require('path');
const { default: fluid, extract } = require('fluid-tailwind');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: {
    files: [
      join(__dirname, 'src/**/!(*.stories|*.spec).{ts,html}'),
      ...createGlobPatternsForDependencies(__dirname),
    ],
    extract,
  },
  theme: {
    screens: {
      xs: '20rem',
      lg: '64rem',
    },
  },
  plugins: [fluid],
};
```

**Comment by draylegend** [comment]
@barvian u r awesome ❤️‍🔥 I had an array instead of object. Now works for me as well!
