### ISSUE TITLE
Unmet peer requirement issues with tailwind-merge

### ISSUE THREAD

**Issue by natemking** [barvian/fluid-tailwind#47]
# Issue
 Most recent version of tailwind-merge is at v2.5.2 and the @fluid-tailwind/tailwind-merge plugin is requesting v2.4.0 which is causing yarn install peer requirement warning when running `yarn install` in yarn v.4.4.1. 

# Workaround
Downgrade current version of tailwind-merge. 

Thanks for building this library . It's a greatly needed tool. This issue isn't a blocker in the least but we would prefer to be running the newest version of tailwind-merge without any yarn install warning/errors.

**Comment by barvian** [comment]
Hi, thanks for the kind words. I relaxed the peer dep in [0.0.3](https://github.com/barvian/fluid-tailwind/releases/tag/%40fluid-tailwind%2Ftailwind-merge%400.0.3) because tailwind-merge 2.5 still supports the experimental feature fluid-tailwind needs. 👍
