### ISSUE TITLE
Type Error with extract function in NextJS TypeScript Setup

### ISSUE THREAD

**Issue by prasadsawant7** [barvian/fluid-tailwind#48]
I'm encountering a type error when using the extract function from fluid-tailwind in my NextJS, TypeScript, TailwindCSS, and ShadCN project. The error occurs when trying to assign extract in the content configuration of the Tailwind config.

Reproduction Steps:

1. Create a NextJS project with TypeScript, TailwindCSS, and ShadCN.
2. Install and configure fluid-tailwind as per the documentation.
3. Import fluid and extract from fluid-tailwind in tailwind.config.ts.
4. Set up the content field with the following configuration:
```
import type { Config } from "tailwindcss";
import fluid, { extract } from "fluid-tailwind";

const config: Config = {
  darkMode: ["class"],
  content: {
    files: [
      "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
      "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
      "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    extract,
  },
  plugins: [fluid],
};

export default config;
```

Expected behavior: The extract function should work without any TypeScript errors, as specified in the documentation.

Actual behavior: The following type error is raised:
```
Type '{ (content: string): string[]; (options: ExtractorOptions): ExtractorFn; }' is not assignable to type 'string | RawFile'.ts(2322)
```

Environment Details:
Next.js Version: v14.2.13
TypeScript Version: v5
TailwindCSS Version: v3.4.1
fluid-tailwind Version: v1.0.3
ShadCN Version: v2.1.0
Node.js Version: v20.17.0
PNPM Version: v9.12.0

Solution: The problem lies with how the content field is structured. Instead of defining content as an array, the correct approach is to use an object with a files field, like this:

```ts
content: {
  files: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  extract,
},
```

By changing the structure, the TypeScript error is resolved, and the configuration works as expected.

Why this should be updated: This oversight might confuse others, as the documentation currently suggests an incorrect structure. I recommend updating the docs or providing a clarification to help users avoid this issue.

**Comment by barvian** [comment]
Hi @prasadsawant7, glad you found a resolution. Where in the docs did you find the incorrect structure? I tried to highlight the object syntax in the installation instructions:

<img width="841" alt="image" src="https://github.com/user-attachments/assets/aef0a2d5-a9c6-4147-a376-156b04c1f856">

**Comment by ynamite** [comment]
I get the same error even with the updated structure with Tailwind 3.4.17 and Fluid TW 1.0.4
```
Type '{ darkMode: "selector"; content: { files: string[]; extract: { (content: string): string[]; (options?: ExtractorOptions | undefined): ExtractorFn; }; }; theme: { ...; }; plugins: any[]; }' is not assignable to type 'UserConfig'.
  Types of property 'content' are incompatible.
    Object literal may only specify known properties, and 'extract' does not exist in type 'ContentFile[] | { relative?: boolean | undefined; files: ContentFile[]; }'.ts(2322)
Object literal may only specify known properties, and 'extract' does not exist in type 'ContentFile[] | { relative?: boolean | undefined; files: ContentFile[]; }'.ts(2353)
types-BTRmm49E.d.mts(77, 5): The expected type comes from property 'content' which is declared here on type 'UserConfig'
```
My config looks like this:
```
import type { Config } from "tailwindcss";
import fluid, { extract, screens, fontSize } from "fluid-tailwind";

const config: Config = {
  darkMode: "selector",
  content: {
    files: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
    extract,
  },
  ...,
  plugins: [
    fluid({
      checkSC144: false,
    }),
};
```
