### ISSUE TITLE
How to make it work with vite-plugin-tailwind-purgecss

### ISSUE THREAD

**Issue by kevpye-fabdata** [barvian/fluid-tailwind#58]
Hello there, firstly thanks got your work on this library. 

I have a question and hope for your help / advice. I want to use this library in my project but I am having difficulty with it when I build my application. I am using the skeleton ui library and they recommend using the tailwind purge css library [here](https://github.com/AdrianGonz97/vite-plugin-tailwind-purgecss) to reduce the size of the css bundle. The problem is this library seems to purge all of your css. Do you have any idea how I can prevent that from happening?

My vite config is below - if I comment out the purgeCss plugin then I don't lose your styles on build:

```
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig, configDefaults } from 'vitest/config';
import { purgeCss } from 'vite-plugin-tailwind-purgecss';
import { svelteTesting } from '@testing-library/svelte/vite';

export default defineConfig({
	plugins: [
		sveltekit(),
		purgeCss(),
		svelteTesting()
	],
	test: {
		// Jest like globals
		globals: true,
		environment: 'jsdom',
		include: ['src/**/*.{test,spec}.{js,ts}'],
		// Extend jest-dom matchers
		setupFiles: ['./setupTest.ts'],
		coverage: {
			reporter: ['text', 'clover', 'json', 'cobertura', 'html'],
			exclude: [
				...configDefaults.exclude,
				// '*.{js,ts,cjs}',
				'**/*.d.{js,ts}',
				'.husky/**/*',
				'.svelte-kit/**/*'
			]
		}
	}
});

```

Many thanks

**Comment by kevpye-fabdata** [comment]
Hi @barvian - many thanks for the super fast response.

I looked into your suggestion but in order to use the purgecss config option it requires enabling legacy mode - which they do not recommend as it was too hungry at removing things. I may have fixed this (at least for now) by adding the following to the tailwind config 
``
safelist: [{ pattern: /(~)./ }] 
``` 

but let me know if you think this is a bad idea  :)

The plugin page mentions the plugin will not even be needed in tailwind v4 as they are introducing a new [Vite plugin](https://tailwindcss.com/blog/tailwindcss-v4-alpha#zero-configuration-content-detection) that will detect and generate the tailwind classes based on the module graph. Hopefully your library will work with that too :)

**Comment by barvian** [comment]
Seems like a good solution to me! I'm also excited about Tailwind v4 and definitely planning to support it 👍
