### ISSUE TITLE
Problem with breakpoints

### ISSUE THREAD

**Issue by aydeeen** [barvian/fluid-tailwind#59]
Great plugin!

Just one issue, when I try to add fluid breakpoints, it doesn't work.
Basically it always behaves like its going from default smallest to default biggest.
In the screenshot, you can see that I added md to lg breakpoint, but it doesn't work for some reason.

![Screenshot 2024-11-11 155442](https://github.com/user-attachments/assets/25753a38-2474-4979-9638-c9cdeadb7d00)

As far as I can see, it adds css but without breakpoints.
Any help would be appreciated.

**Comment by barvian** [comment]
Hi 👋, thanks for the kind words! Is it working [like this](https://play.tailwindcss.com/gs7fVBtw8M?layout=horizontal&size=770x720&file=config) for you locally?

**Comment by aydeeen** [comment]
You're welcome!
I started new project with ti and I am loving it.
Yea it works exactly like that.
Maybe I was wrong. I thought that when it for example reaches "sm" breakpoint, that padding will be 0 in that example

**Comment by barvian** [comment]
Ah yeah, the fluid variant (`~md/lg` in this case) only changes the start/end breakpoints for the `clamp()` and doesn't wrap the whole thing in media queries 👍 . You can combine them with media queries if you want though, e.g.

```html
<div class="md:max-lg:~md/lg:~p-5/16">
```
[Sandbox](https://play.tailwindcss.com/OTUssXISsW?layout=horizontal&size=722x720)

Is that closer to what you were looking for?

**Comment by barvian** [comment]
No problem! ✌️
