### ISSUE TITLE
Turn Off WCAG Success Criteria/Accessibility Enforcement:

### ISSUE THREAD

**Issue by robotecha** [barvian/fluid-tailwind#60]
Hi, 

I was wondering, Is there a way to disable the WCAG Success Criterion or other Accessibility Enforcements? I keep getting errors in my output css, but I don't need to be concerned with the Accessibility Enforcement for the site I'm building.

Thanks

**Comment by barvian** [comment]
Hi 👋, yes you can pass this option to your Tailwind config ([docs](https://fluid.tw/#fluid-type-accessibility-checks):
```js
// tailwind.config.js
export default {
  // ...
  plugins: [
    fluid({
      checkSC144: false // default: true
    })
  ]
}
```
