### ISSUE TITLE
Understanding Issue with Fluid Typography and @apply

### ISSUE THREAD

**Issue by olien** [barvian/fluid-tailwind#61]
I’m encountering an issue with fluid typography in my Tailwind CSS project using the @apply directive. The behavior is inconsistent when I switch between 5xl and 6xl sizes. Here’s the detailed breakdown:

**Code that works:**
`.content h1 {
    @apply ~text-xl/5xl
            ~mt-2/4 ~mb-4/6;
}`

**Result:**
`.content h1 {
  font-size: clamp(1.25rem,0rem + 3.13vw,3rem)/* fluid type from 1.25rem at 40rem to 3rem at 96rem */;
  line-height: clamp(1.75rem,0.86rem + 2.23vw,3rem)/* fluid from 1.75rem at 40rem to 3rem at 96rem */;
  margin-top: clamp(0.5rem,0.14rem + 0.89vw,1rem)/* fluid from 0.5rem at 40rem to 1rem at 96rem */;
  margin-bottom: clamp(1rem,0.64rem + 0.89vw,1.5rem)/* fluid from 1rem at 40rem to 1.5rem at 96rem */;
}`

This works perfectly as expected. The font size and other properties adjust fluidly.

---

**Code that doesn’t work:**
`.content h1 {
    @apply ~text-xl/6xl
            ~mt-2/4 ~mb-4/6;
}`

**Result:**

`.content h1 {
  font-size: /* not fluid type from 1.25rem at 40rem to 3.75rem at 96rem: Fails WCAG SC 1.4.4 at i.e. 200rem */;
  line-height: clamp(1.75rem,0.32rem + 3.57vw,3.75rem)/* fluid from 1.75rem at 40rem to 3.75rem at 96rem */;
  margin-top: clamp(0.5rem,0.14rem + 0.89vw,1rem)/* fluid from 0.5rem at 40rem to 1rem at 96rem */;
  margin-bottom: clamp(1rem,0.64rem + 0.89vw,1.5rem)/* fluid from 1rem at 40rem to 1.5rem at 96rem */;
}`

---

**Problem**

When changing ~text-xl/5xl to ~text-xl/6xl, the fluid font size fails. The generated CSS for font-size includes a comment:
/* not fluid type from 1.25rem at 40rem to 3.75rem at 96rem: Fails WCAG SC 1.4.4 at i.e. 200rem */.

I don’t understand why this happens. Why is the fluid behavior breaking for 6xl, but it works perfectly for 5xl? All other properties like line-height, margin-top, and margin-bottom remain fluid.

---

This issue is blocking my workflow, and I would appreciate any insights or fixes. Thank you!

**Comment by barvian** [comment]
Hi, the second range creates an accessibility violation so the plugin won't generate it by default. You can find more info including how to disable that check in [this section of the docs](https://fluid.tw/#fluid-type-accessibility-checks) 👋

**Comment by olien** [comment]
ok. Thanks!
