### ISSUE TITLE
[Question] Integration with tailwind-typography

### ISSUE THREAD

**Issue by FatChicken277** [barvian/fluid-tailwind#64]
There is any way to integrate fluid with [@tailwindcss/typography](https://github.com/tailwindlabs/tailwindcss-typography)?? i would be awesome

**Comment by FatChicken277** [comment]
they have some classes like prose-sm prose-md prose-lg it would be great if we can use like ~pose-md/prose-lg, im kinda new at tailwind so idk if this is possible, thx

**Comment by barvian** [comment]
Hi! Yes, this is possible with e.g. `prose-h1:~text-xl/2xl`. See this [Tailwind Play](https://play.tailwindcss.com/K37O8iCtZY) for an example and [this discussion](https://github.com/barvian/fluid-tailwind/discussions/34) for more info. 👋

**Comment by barvian** [comment]
In case I didn't answer your original question, `~prose-md/lg` wouldn't work out of the box unfortunately.

**Comment by FatChicken277** [comment]
but there is any way to acomplish something like that? bc your implementations brokes the sizing rules of the tailwind-typography, there is some way to take typography sizing and base on that use fluid?

**Comment by barvian** [comment]
I think all of the font-sizes and margins inside prose are `em`s, so you could do something like this to make the overall scale fluid: `prose ~text-sm/lg` ([sandbox](https://play.tailwindcss.com/z8qWCxhozN))
